version: '3'

shopt: [globstar]

includes:
  api:
    taskfile: ./api/Taskfile.yaml
    dir: ./api
  datum-service:
    taskfile: ./packages/datum-service/Taskfile.yaml
    dir: ./packages/datum-service
  datum-web:
    taskfile: ./packages/datum-web/Taskfile.yaml
    dir: ./packages/datum-web

tasks:
  default:
    cmds:
      - task --list-all

  install-tools:
    deps:
      - api:install-tools
