package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datum-cloud/datum-os/internal/ent/generated"
	"github.com/datum-cloud/datum-os/pkg/rout"
)

// CreatePhoneNumber is the resolver for the createPhoneNumber field.
func (r *mutationResolver) CreatePhoneNumber(ctx context.Context, input generated.CreatePhoneNumberInput) (*PhoneNumberCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).PhoneNumber.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "phonenumber"}, r.logger)
	}

	return &PhoneNumberCreatePayload{
		PhoneNumber: res,
	}, nil
}

// CreateBulkPhoneNumber is the resolver for the createBulkPhoneNumber field.
func (r *mutationResolver) CreateBulkPhoneNumber(ctx context.Context, input []*generated.CreatePhoneNumberInput) (*PhoneNumberBulkCreatePayload, error) {
	return r.bulkCreatePhoneNumber(ctx, input)
}

// CreateBulkCSVPhoneNumber is the resolver for the createBulkCSVPhoneNumber field.
func (r *mutationResolver) CreateBulkCSVPhoneNumber(ctx context.Context, input graphql.Upload) (*PhoneNumberBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreatePhoneNumberInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreatePhoneNumber(ctx, data)
}

// UpdatePhoneNumber is the resolver for the updatePhoneNumber field.
func (r *mutationResolver) UpdatePhoneNumber(ctx context.Context, id string, input generated.UpdatePhoneNumberInput) (*PhoneNumberUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).PhoneNumber.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "phonenumber"}, r.logger)
	}
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, &res.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "phonenumber"}, r.logger)
	}

	return &PhoneNumberUpdatePayload{
		PhoneNumber: res,
	}, nil
}

// DeletePhoneNumber is the resolver for the deletePhoneNumber field.
func (r *mutationResolver) DeletePhoneNumber(ctx context.Context, id string) (*PhoneNumberDeletePayload, error) {
	if err := withTransactionalMutation(ctx).PhoneNumber.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "phonenumber"}, r.logger)
	}

	if err := generated.PhoneNumberEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &PhoneNumberDeletePayload{
		DeletedID: id,
	}, nil
}

// PhoneNumber is the resolver for the phoneNumber field.
func (r *queryResolver) PhoneNumber(ctx context.Context, id string) (*generated.PhoneNumber, error) {
	res, err := withTransactionalMutation(ctx).PhoneNumber.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "phonenumber"}, r.logger)
	}

	return res, nil
}
