package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/datum-cloud/datum-os/internal/ent/generated"
	"github.com/datum-cloud/datum-os/pkg/rout"
)

// CreateVendor is the resolver for the createVendor field.
func (r *mutationResolver) CreateVendor(ctx context.Context, input generated.CreateVendorInput) (*VendorCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).Vendor.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "vendor"}, r.logger)
	}

	return &VendorCreatePayload{
		Vendor: res,
	}, nil
}

// CreateBulkVendor is the resolver for the createBulkVendor field.
func (r *mutationResolver) CreateBulkVendor(ctx context.Context, input []*generated.CreateVendorInput) (*VendorBulkCreatePayload, error) {
	return r.bulkCreateVendor(ctx, input)
}

// CreateBulkCSVVendor is the resolver for the createBulkCSVVendor field.
func (r *mutationResolver) CreateBulkCSVVendor(ctx context.Context, input graphql.Upload) (*VendorBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateVendorInput](input)
	if err != nil {
		r.logger.Errorw("failed to unmarshal bulk data", "error", err)

		return nil, err
	}

	return r.bulkCreateVendor(ctx, data)
}

// UpdateVendor is the resolver for the updateVendor field.
func (r *mutationResolver) UpdateVendor(ctx context.Context, id string, input generated.UpdateVendorInput) (*VendorUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).Vendor.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "vendor"}, r.logger)
	}
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, &res.OwnerID); err != nil {
		r.logger.Errorw("failed to set organization in auth context", "error", err)

		return nil, ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "vendor"}, r.logger)
	}

	return &VendorUpdatePayload{
		Vendor: res,
	}, nil
}

// DeleteVendor is the resolver for the deleteVendor field.
func (r *mutationResolver) DeleteVendor(ctx context.Context, id string) (*VendorDeletePayload, error) {
	if err := withTransactionalMutation(ctx).Vendor.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "vendor"}, r.logger)
	}

	if err := generated.VendorEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &VendorDeletePayload{
		DeletedID: id,
	}, nil
}

// Vendor is the resolver for the vendor field.
func (r *queryResolver) Vendor(ctx context.Context, id string) (*generated.Vendor, error) {
	res, err := withTransactionalMutation(ctx).Vendor.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "vendor"}, r.logger)
	}

	return res, nil
}
