services:
  feature-flags:
    image: gofeatureflag/go-feature-flag:latest
    container_name: feature-flags
    restart: always
    environment:
      - EXPORTER_KIND=log
      - FILEFORMAT=yaml
      - LISTEN=1031
      - POLLINGINTERVAL=1000
      - RETRIEVER_KIND=file
      - RETRIEVER_PATH=/goff/flags.goff.yaml
      - STARTWITHRETRIEVERERROR=false
    ports:
      - '1031:1031'
    volumes:
      - type: bind
        source: ./configs/feature-flags/local.flags.goff.yaml
        target: /goff/flags.goff.yaml

volumes:
  redis_data:
    driver: local
