version: '3'

includes:
  codegen:
    taskfile: ./packages/codegen/Taskfile.yaml
    dir: ./packages/codegen

env:
  ENV: ./config

tasks:
  default:
    cmds:
      - task --list-all

  build:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: build all apps and package
    cmd: bun run build

  install:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: install the dependencies listed in package.json
    cmds:
      - bun install

  dev:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: develop all apps
    cmds:
      - task: install
      - bun dev

  dev:docs:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: develop docs
    cmds:
      - task: install
      - bun dev --filter={apps/docs}

  dev:operator:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: develop operator
    cmds:
      - task: install
      - bun dev --filter={apps/operator}

  dev:web:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: develop web
    cmds:
      - task: install
      - bun dev --filter={apps/web}

  dev:storybook:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: develop storybook
    cmds:
      - task: install
      - bun dev --filter={apps/storybook}

  build:web:
    dotenv: ['.env', '{{.ENV}}/.env']
    desc: build web
    cmds:
      - task: install
      - bun run build --filter={apps/web}
